name: Bad CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        run: sudo apt-get install python3 python3-pip -y
      - name: Install dependencies
        run: pip3 install pytest
      - name: Run tests
        run: pytest test_app.py
      - name: Deploy (fake)
        run: echo "Deploying..."
